# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9847f8e5914ebbaa1cfd368026719b58d036f190b27fb4919b3888c864309d637a909ff768fc5ea5345f977451fa740f1c9d47e9a5dfd48f3fbc1d0d5d897217

test:
  secret_key_base: 7125b43a5203d6684f61dedc071a005d39d74537a491ac4b4f56189e888356cce71c6b4f9249c15f045cf38c13462de799daf595cb88c3c185b9dd381f813667

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
